<a href="https://colab.research.google.com/github/SarahGraceMaclean/Udemy-Complete-Guide-to-TensorFlow-for-Deep-Learning-with-Python/blob/master/Section_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==1.3.0

     |████████████████████████████████| 43.6MB 422kB/s 
     |████████████████████████████████| 1.6MB 33.2MB/s 
     |████████████████████████████████| 890kB 38.5MB/s 
  Stored in directory: /root/.cache/pip/wheels/50/ae/f9/d2b189788efcf61d1ee0e36045476735c838898eef1cad6e29
Successfully built html5lib
ERROR: stable-baselines 2.2.1 has requirement tensorflow>=1.5.0, but you'll have tensorflow 1.3.0 which is incompatible.
ERROR: magenta 0.3.19 has requirement tensorflow>=1.12.0, but you'll have tensorflow 1.3.0 which is incompatible.
  Found existing installation: html5lib 1.0.1
    Uninstalling html5lib-1.0.1:
      Successfully uninstalled html5lib-1.0.1
  Found existing installation: bleach 3.1.0
    Uninstalling bleach-3.1.0:
      Successfully uninstalled bleach-3.1.0
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


1.13.1


In [0]:
import tensorflow as tf
print(tf.__version__)

1.3.0


# **Tensorflow Basic Syntax**

In [0]:
hello = tf.constant("Hello ")
world = tf.constant("World")
type(hello)

tensorflow.python.framework.ops.Tensor

In [0]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [0]:
with tf.Session() as sess:
  result = sess.run(hello+world)

In [0]:
print(result)

b'Hello World'


In [0]:
a = tf.constant(10)
b = tf.constant(20)
type(a)

tensorflow.python.framework.ops.Tensor

In [0]:
a+b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [0]:
with tf.Session() as sess:
  result = sess.run(a+b)

In [0]:
result

30

In [0]:
const = tf.constant(10)

In [0]:
fill_mat = tf.fill((4,4),10)

In [0]:
myzeros = tf.zeros((4,4))

In [0]:
myones = tf.ones((4,4))

In [0]:
myrandn = tf.random_normal((4,4), mean = 0, stddev = 1.0)

In [0]:
myrandu = tf.random_uniform((4,4), minval = 0, maxval = 1)

In [0]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [0]:
my_ops = [const,fill_mat, myzeros,myones, myrandn, myrandu]

In [0]:
sess = tf.InteractiveSession()    #allows all cells below this one to still be part of the session

In [0]:
for op in my_ops:
  print(sess.run(op))
  print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.08484492  1.0421869  -0.46068916  1.6951287 ]
 [ 0.6593918   0.95552504 -0.47194356  0.12266005]
 [ 1.2564198   1.4884942  -0.52101654 -2.0250022 ]
 [ 0.2569832   0.36935815  0.92310596  0.49049044]]


[[0.5414866  0.81911063 0.8993839  0.87832475]
 [0.55857754 0.4241575  0.34407878 0.75101924]
 [0.8410381  0.95540607 0.6758945  0.6667007 ]
 [0.2680335  0.4480555  0.07160783 0.6587632 ]]




In [0]:
a = tf.constant([[1,2],
                [3,4]])

In [0]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [0]:
b = tf.constant([[10],[100]])

In [0]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [0]:
result = tf.matmul(a,b)

In [0]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [0]:
result.eval()

array([[210],
       [430]], dtype=int32)

# Tensorflow Graphs 

In [0]:
n1 = tf.constant(1)
n2 = tf.constant(2)
n3 = n1+n2

In [0]:
with tf.Session() as sess:
  result = sess.run(n3)

In [0]:
print(result)

3


In [0]:
print(n3)

Tensor("add_4:0", shape=(), dtype=int32)


In [0]:
print(tf.get_default_graph())

In [0]:
g = tf.Graph()

In [0]:
print(g)

In [0]:
graph_one = tf.get_default_graph()

In [0]:
print(graph_one)

In [0]:
graph_two = tf.Graph()

In [0]:
print(graph_two)

In [0]:
with graph_two.as_default():
  print(graph_two is tf.get_default_graph())

True


In [0]:
print(graph_two is tf.get_default_graph())

False


# **Variables and Placeholders**

In [0]:
sess = tf.InteractiveSession()

In [0]:
my_tensor = tf.random_uniform((4,4),0,1)

In [0]:
my_tensor

<tf.Tensor 'random_uniform_1:0' shape=(4, 4) dtype=float32>

In [0]:
my_var = tf.Variable(initial_value = my_tensor)

In [0]:
print(my_var)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32_ref>


In [0]:
#sess.run(my_var)

In [0]:
init = tf.global_variables_initializer()

In [0]:
sess.run(init)

In [0]:
sess.run(my_var)

array([[0.0665462 , 0.98238146, 0.376302  , 0.33096302],
       [0.5724422 , 0.5030707 , 0.93631303, 0.31718636],
       [0.55393577, 0.12764072, 0.3631096 , 0.7953737 ],
       [0.04426956, 0.07786191, 0.1441865 , 0.43492985]], dtype=float32)

In [0]:
ph = tf.placeholder(tf.float32)